# Generated by Django 2.1.2 on 2018-12-22 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=10)),
                ('created', models.DateTimeField(editable=False)),
                ('band_number', models.CharField(max_length=32)),
                ('wing_size', models.FloatField()),
                ('sex', models.CharField(choices=[('U', 'Unknown'), ('M', 'Male'), ('F', 'Female')], default='U', max_length=5)),
                ('sex_how', models.CharField(choices=[('BO', 'Behavioral observation'), ('BP', 'Brood patch'), ('CC', 'Combination of characteristics/measurements'), ('CL', 'Cloaca'), ('DN', 'DNA/chromosome analysis'), ('EG', 'Egg in oviduct'), ('EY', 'Eye color'), ('FS', 'Feather Shape (Primaries or tail)'), ('IC', 'Inconclusive, Conflicting'), ('LL', 'Laparotomy/laparoscopy'), ('MB', 'Mouth/bill'), ('NA', 'Not attempted'), ('OT', 'Other'), ('PL', 'Body Plumage'), ('RC', 'Sexed upon recapture'), ('TL', 'Tail length'), ('WL', 'Wing length')], default='NA', max_length=10, verbose_name='Method used to determine sex')),
                ('age', models.CharField(choices=[('U', 'Unknown'), ('AHY', 'After Hatching Year'), ('HY', 'Hatching Year'), ('J', 'Juvenile'), ('L', 'Local'), ('SY', 'Second Year'), ('ASY', 'After Second Year'), ('TY', 'Third Year'), ('ATY', 'After Third Year')], default='U', max_length=5)),
                ('age_how', models.CharField(choices=[('AM', 'Auxiliary Marker'), ('BO', 'Behavioral observation'), ('BP', 'Brood patch'), ('BU', 'Bursa of Fabricius'), ('CA', 'Calendar'), ('CC', 'Combination of characteristics/measurements'), ('CL', 'Cloaca'), ('EG', 'Egg in oviduct'), ('EY', 'Eye color'), ('FB', 'Fault bar'), ('FF', 'Flight feathers (remiges), condition or color'), ('IC', 'Inconclusive, Conflicting   '), ('LP', 'Molt limit present  '), ('MB', 'Mouth/bill  '), ('MR', 'Actively-molting remiges'), ('NA', 'Not attempted'), ('NF', 'Nestling recently fledged, incapable of powered flight'), ('NL', 'No molt limit'), ('NN', 'Nestling in nest (altricials), downy young (precocials)'), ('OT', 'Other'), ('PC', 'Primary covert wear and/or shape'), ('PL', 'Body Plumage'), ('RC', 'Re-captured bird with USGS band'), ('SK', 'Skull'), ('TL', 'Tail length'), ('TS', 'Tail shape or wear')], default='NA', max_length=10, verbose_name='Method used to determine age')),
                ('culmen', models.FloatField(null=True, verbose_name='Bill or beak measurement')),
                ('corrugation', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('weight', models.FloatField()),
                ('molt_flight', models.CharField(max_length=10)),
                ('molt_body', models.CharField(max_length=10)),
                ('gorget', models.IntegerField()),
                ('skull', models.CharField(max_length=10)),
                ('notes', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
