# Generated by Django 2.1.2 on 2018-10-14 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('birds', '0001_initial'),
        ('nets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='bander',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bander', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bird',
            name='data_manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bird',
            name='net',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='nets.Net'),
        ),
    ]
